package com.miagendaia.mi_agenda_ia
import android.app.*
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.os.*
import androidx.core.app.NotificationCompat
class AlarmService:Service(){private var player:MediaPlayer?=null;private var vibrator:Vibrator?=null;private var wake:PowerManager.WakeLock?=null;override fun onCreate(){super.onCreate();createChannel()} override fun onStartCommand(intent:Intent?,flags:Int,startId:Int):Int{when(intent?.action){ACTION_STOP->{stopPlayback();stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();return START_NOT_STICKY};ACTION_START->{val id=intent.getStringExtra("id")?:"";val title=intent.getStringExtra("title")?:"Recordatorio";val mode=intent.getStringExtra("alertMode")?:"soundAndVibration";startForeground(notificationId(id),notification(id,title,mode));startPlayback(mode)}};return START_NOT_STICKY}
 private fun startPlayback(mode:String){stopPlayback();val pm=getSystemService(Context.POWER_SERVICE) as PowerManager;wake=pm.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"MiAgendaIA:AlarmWakeLock").apply{acquire(30*60*1000L)};val sound=mode=="soundAndVibration"||mode=="strong"||mode=="soundOnly";val vib=mode=="soundAndVibration"||mode=="strong"||mode=="vibrationOnly";if(sound){val afd=resources.openRawResourceFd(R.raw.alarm_tone);player=MediaPlayer().apply{setAudioAttributes(AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION).build());setDataSource(afd.fileDescriptor,afd.startOffset,afd.length);afd.close();isLooping=true;setVolume(1f,1f);prepare();start()}};if(vib){vibrator=if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.S)(getSystemService(Context.VIBRATOR_MANAGER_SERVICE) as VibratorManager).defaultVibrator else @Suppress("DEPRECATION")(getSystemService(Context.VIBRATOR_SERVICE) as Vibrator);val pattern=if(mode=="strong") longArrayOf(0,1200,250,1200,250) else longArrayOf(0,800,400,800,400);if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O)vibrator?.vibrate(VibrationEffect.createWaveform(pattern,0)) else @Suppress("DEPRECATION") vibrator?.vibrate(pattern,0)}}
 private fun stopPlayback(){try{player?.stop()}catch(_:Exception){};player?.release();player=null;vibrator?.cancel();vibrator=null;if(wake?.isHeld==true)wake?.release();wake=null}
 private fun notification(id:String,title:String,mode:String):Notification{val launch=packageManager.getLaunchIntentForPackage(packageName)?:Intent(this,MainActivity::class.java);val open=PendingIntent.getActivity(this,notificationId(id),launch.apply{addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)},PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);fun action(a:String,code:Int):PendingIntent{val i=Intent(this,AlarmActionReceiver::class.java).apply{this.action=a;putExtra("id",id);putExtra("title",title);putExtra("alertMode",mode)};return PendingIntent.getBroadcast(this,code,i,PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)};val base=notificationId(id)*10;return NotificationCompat.Builder(this,CHANNEL).setSmallIcon(R.mipmap.ic_launcher).setContentTitle("Mi Agenda IA").setContentText(title).setStyle(NotificationCompat.BigTextStyle().bigText(title)).setCategory(NotificationCompat.CATEGORY_ALARM).setPriority(NotificationCompat.PRIORITY_MAX).setOngoing(true).setAutoCancel(false).setColor(Color.rgb(0,95,228)).setContentIntent(open).setFullScreenIntent(open,true).addAction(0,"OK",action(AlarmActionReceiver.ACTION_OK,base+1)).addAction(0,"Posponer 10 min",action(AlarmActionReceiver.ACTION_SNOOZE,base+2)).addAction(0,"Reprogramar",action(AlarmActionReceiver.ACTION_REPROGRAM,base+3)).build()}
 private fun createChannel(){if(Build.VERSION.SDK_INT<Build.VERSION_CODES.O)return;val m=getSystemService(NotificationManager::class.java);m.createNotificationChannel(NotificationChannel(CHANNEL,"Alarmas de Mi Agenda IA",NotificationManager.IMPORTANCE_HIGH).apply{description="Alarmas persistentes";setSound(null,null);enableVibration(false);lockscreenVisibility=Notification.VISIBILITY_PUBLIC})}
 override fun onDestroy(){stopPlayback();super.onDestroy()} override fun onBind(intent:Intent?)=null
 companion object{const val CHANNEL="agenda_alarm_runtime_v3";const val ACTION_START="com.miagendaia.alarm.START";const val ACTION_STOP="com.miagendaia.alarm.STOP";fun stopAlarm(context:Context){context.startService(Intent(context,AlarmService::class.java).apply{action=ACTION_STOP})}private fun notificationId(id:String)=(id.hashCode() and 0x7fffffff).coerceAtLeast(1)}}
